'''
PANDAS:
 MAIS USADA NO GERAL
 TRATA O EXCEL COMO UMA BASE DE DADOS
 FAZ O QUE QUISER COM O ARQUIVO 
 PODE DESFAZER A ESTRUTURA ORIGINAL DO ARQUIVO CASO QUEIRA EDITAR

 OPENPYXL
 TRATA O EXCEL COMO UMA PLANILHA MESMO QUE POSSA TER VARIAS COISAS
 EDITA "COMO SE FOSSE UM VBA"
 MENOS EFICIENTE 
 MANTEM A ESTRUTURA ORIGINAL DO ARQUIVO, MAS CUIDADO PORQUE NAO NECESSARIAMENTE TUDO, TEM QUE TESTAR

'''

